name: AdsYieldAdapterSample
options:
  bundleIdPrefix: com.adsyield.adapter
  deploymentTarget:
    iOS: "13.0"
  xcodeVersion: "16.2"
settings:
  SWIFT_VERSION: "5"
targets:
  AdsYieldAdapterSample:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources
    info:
      path: Sources/Info.plist
    settings:
      INFOPLIST_FILE: Sources/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.adsyield.adapter.sample
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_ALLOWED: "NO"
